[package]
name = "bevy_thinlto_error"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.15.1", default-features = false, features = ["dynamic_linking"] }


[profile.release]
lto = "thin"

[profile.dev]
lto = "thin"